# Generated by Django 2.1.2 on 2018-10-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181013_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiredurl',
            options={'ordering': ('-created_timestamp', 'short_url')},
        ),
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ('-created_timestamp', 'short_url')},
        ),
        migrations.RenameField(
            model_name='expiredurl',
            old_name='created_time',
            new_name='created_timestamp',
        ),
        migrations.RenameField(
            model_name='expiredurl',
            old_name='expired_time',
            new_name='expired_timestamp',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='created_time',
            new_name='created_timestamp',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='expired_time',
            new_name='expired_timestamp',
        ),
    ]
